import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // Warm editorial paper system, mirroring the reference site's real tokens
  // (cream page bg, warm near-black ink, subtle raised/depth surfaces, plus
  // an IBM Plex Serif display voice for headlines). No red accent, no bright
  // primary — the mood is expensive stationery, not dashboard SaaS.
  '--slot4-page-bg': '#f7f7f2',
  '--slot4-page-text': '#191818',
  '--slot4-panel-bg': '#efede7',
  '--slot4-surface-bg': '#fcfbf7',
  '--slot4-muted-text': '#4e374a',
  '--slot4-soft-muted-text': '#807e7c',
  '--slot4-accent': '#1e1c1b',
  '--slot4-accent-fill': '#1e1c1b',
  '--slot4-accent-hover': '#302023',
  '--slot4-accent-soft': '#e1dcd5',
  '--slot4-on-accent': '#f7f7f2',
  '--slot4-highlight': '#c56a21',
  '--slot4-highlight-soft': '#f0e3d4',
  '--slot4-dark-bg': '#1e1c1b',
  '--slot4-dark-surface': '#22201f',
  '--slot4-dark-raised': '#2a2827',
  '--slot4-dark-text': '#f7f7f2',
  '--slot4-dark-muted': 'rgba(247,247,242,0.66)',
  '--slot4-dark-border': 'rgba(247,247,242,0.14)',
  '--slot4-dark-glow': 'rgba(197,106,33,0.32)',
  '--slot4-media-bg': '#e1dcd5',
  '--slot4-cream': '#f7f7f2',
  '--slot4-warm': '#efede7',
  '--slot4-lavender': '#efede7',
  '--slot4-gray': '#e1dcd5',
  '--slot4-body-gradient': 'none',
  '--slot4-radius-sm': '0.625rem',
  '--slot4-radius-md': '1rem',
  '--slot4-radius-lg': '1.5rem',
  '--slot4-radius-pill': '999px',
  '--editable-page-bg': '#f7f7f2',
  '--editable-page-text': '#191818',
  '--editable-container': '1360px',
  '--editable-border': '#e1dcd5',
  '--editable-nav-bg': '#f7f7f2',
  '--editable-nav-text': '#191818',
  '--editable-nav-active': '#1e1c1b',
  '--editable-nav-active-text': '#f7f7f2',
  '--editable-cta-bg': '#1e1c1b',
  '--editable-cta-text': '#f7f7f2',
  '--editable-search-bg': '#fcfbf7',
  '--editable-footer-bg': '#1e1c1b',
  '--editable-footer-text': '#f7f7f2',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkSurfaceBg: 'bg-[var(--slot4-dark-surface)]',
  darkRaisedBg: 'bg-[var(--slot4-dark-raised)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  darkMutedText: 'text-[var(--slot4-dark-muted)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-[var(--slot4-dark-border)]',
  shadow: 'shadow-[0_1px_2px_rgba(30,28,27,0.05)]',
  shadowStrong: 'shadow-[0_4px_18px_rgba(30,28,27,0.08)]',
  shadowLg: 'shadow-[0_24px_60px_-20px_rgba(30,28,27,0.22)]',
  shadowAccent: 'shadow-[0_14px_34px_-12px_rgba(30,28,27,0.28)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(30,28,27,0.02),rgba(30,28,27,0.68))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionNarrow: 'mx-auto w-full max-w-4xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
    sectionYLg: 'py-16 sm:py-20 lg:py-28',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    eyebrowOnDark: 'text-xs font-semibold uppercase tracking-[0.28em] text-white/70',
    heroTitle: 'text-4xl font-semibold leading-[1.08] tracking-[-0.02em] sm:text-5xl lg:text-[3.25rem]',
    display: 'text-[2.75rem] font-semibold leading-[1.04] tracking-[-0.03em] sm:text-6xl lg:text-7xl',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.02em] sm:text-4xl',
    statNumber: 'text-4xl font-bold tracking-[-0.02em] sm:text-5xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    cardHover: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow} transition duration-300 hover:-translate-y-1 hover:border-[var(--slot4-accent)]/30 hover:shadow-[0_20px_45px_-18px_rgba(0,0,0,0.22)]`,
    soft: `rounded-2xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-2xl ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
    darkCard: `rounded-2xl border ${editablePalette.darkBorder} ${editablePalette.darkSurfaceBg} ${editablePalette.darkText}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:bg-[var(--slot4-accent-hover)] active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:bg-[var(--slot4-accent-hover)] active:scale-[0.98]`,
    onDark: `inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-bold text-[var(--slot4-dark-bg)] transition duration-200 hover:bg-white/90 active:scale-[0.98]`,
    ghostOnDark: `inline-flex items-center justify-center gap-2 rounded-full border border-white/25 px-6 py-3 text-sm font-bold text-white transition duration-200 hover:border-white/50 hover:bg-white/10 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-2xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_45px_-18px_rgba(0,0,0,0.22)]',
    liftSm: 'transition duration-300 hover:-translate-y-0.5',
    fade: 'transition duration-300 hover:opacity-80',
    zoom: 'overflow-hidden [&_img]:transition [&_img]:duration-500 hover:[&_img]:scale-[1.06]',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
